### ISSUE TITLE
How do I use this ??? I want to be able to do this with my glossika! Thank you for doing this!

### ISSUE THREAD

**Issue by gabearroyo1114** [chicoria/glossika-playlist#1]

**Comment by chicoria** [comment]
Hi, the Github is open platform to share source code among developer community. 

I created this repository as an experimental script to generate my own playlist based on the glossika schedule for the course I have bought  (english to german _ ENDE ) and I am using the 18 weeks schedule provided by glossika. 

So, in order to generate your playlist you have to be able to run this script in your machine which requires coding skills. 

As I have said it totally experimental and made for my own use.  

Which course  (source and target language ) are you studying ? Which schedule ?

**Comment by gabearroyo1114** [comment]
I am doing Mandarin Chinese and Arabic I'm am doing 9 months relaxed schedule. I really wish I knew how to run this script it would help out so many people. Thank you I wanted to do this just didn't know how to do it.

**Comment by chicoria** [comment]
Hey @gabearroyo1114 , I have generated the 9 months relaxed schedule for Chinese Mandarin to Egypt Arabic.

Take a look on the file. 
https://github.com/chicoria/my-glossika-playlist/blob/master/ZSARE_9-Month-Relaxed-Training-43weeks.txt.m3u

Considering you have download the folder structure by Glossika place the playlist file in folders : 

Fluency/
**ZSARE_9-Month-Relaxed-Training-43weeks.txt.m3u**
ZSARE-F1-GMS/
ZSARE-F2-GMS/
ZSARE-F3-GMS/
ZSARE-F1-GSR/
ZSARE-F2-GSR/
ZSARE-F3-GSR/

**Comment by gabearroyo1114** [comment]
That's amazing!!! Thanks so much!!!
